### PR TITLE
.gitignore: ignore .ghc.environment.* files

### PR DESCRIPTION
**Pull request by vaibhavsagar**
IMO this is a misfeature in `cabal-install` and should never have been added in the first place.

### CODE REVIEW

**Comment by i-am-tom** [comment]
What are the disadvantages to this file? The only thing I know about it is that it makes `ghci` work properly without any commands, which seems pretty useful; is there something else going on?

**Comment by vaibhavsagar** [comment]
See https://github.com/haskell/cabal/issues/4542 and https://www.reddit.com/r/haskell/comments/9a6fg4/package_environment_files_run_counter_to/

**Comment by i-am-tom** [comment]
Consider me converted!

**Comment by vaibhavsagar** [comment]
Thanks!

**Pull request merged**
